# Only put things in this file that we want in *every* environment
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER:-admin}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-admin}
      POSTGRES_DB: ${PSQL_DATABASE:-newsletter}